### ISSUE TITLE
Scrolling issues with XLSX files

### ISSUE THREAD

**Issue by reviewher** [AGhost-7/sheet-cli#2] opened 2017-05-15 03:05 UTC
Very neat project!  With small worksheets the current version throws an error:

```
/usr/local/lib/node_modules/sheet-cli/index.js:21
			return formattingMappings[cell.type](cell.value)
			                                    ^

TypeError: formattingMappings[cell.type] is not a function
    at row.map (/usr/local/lib/node_modules/sheet-cli/index.js:21:40)
    at Array.map (native)
    at sheet.rows.map (/usr/local/lib/node_modules/sheet-cli/index.js:20:14)
    at Array.map (native)
    at formatData (/usr/local/lib/node_modules/sheet-cli/index.js:19:20)
    at exports.display (/usr/local/lib/node_modules/sheet-cli/index.js:27:15)
    at exports.main (/usr/local/lib/node_modules/sheet-cli/index.js:58:2)
    at Object.<anonymous> (/usr/local/lib/node_modules/sheet-cli/index.js:62:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

With large worksheets, scrolling beyond the end to the right throws:

```
TypeError: Cannot read property 'toString' of null
    at row.map (/usr/local/lib/node_modules/sheet-cli/lib/table.js:338:32)
    at Array.map (native)
    at slice.map (/usr/local/lib/node_modules/sheet-cli/lib/table.js:338:14)
    at Array.map (native)
    at TableRenderer.proto.render (/usr/local/lib/node_modules/sheet-cli/lib/table.js:337:15)
    at Box.<anonymous> (/usr/local/lib/node_modules/sheet-cli/lib/table.js:401:30)
    at Box.EventEmitter._emit (/usr/local/lib/node_modules/sheet-cli/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/usr/local/lib/node_modules/sheet-cli/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/usr/local/lib/node_modules/sheet-cli/node_modules/blessed/lib/widgets/screen.js:602:15)
    at emitTwo (events.js:106:13)
```

**Comment by AGhost-7** [comment] 2017-05-18 22:13
Thanks for reporting.

Sounds like the first issue is caused by not handling a certain type of cell. Probably going to work on this over the weekend.

edit: yea missing boolean in there.

**Comment by AGhost-7** [comment] 2017-11-13 23:55
@reviewher Closing this since I think the last issue was fixed by recent changes. Feel free to reopen if its still an issue.

**Closed as completed by AGhost-7** 2017-11-13 23:55 UTC
Labels: bug
